version: 2.1
orbs:
  #  https://github.com/codecov/codecov-circleci-orb/blob/v1.0.4/orb.yml
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: golang:latest
        environment:
          CXX: /usr/bin/g++
          CC: /usr/bin/gcc
          GOPATH: /go
          PROJECT_HOME: /go/srCODECOV_TOKEN="a34496a3-1262-4113-83c1-c14061b49a4c"c/github.com/edwardstock/bip39go
          GOBIN: /go/bin
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: apt-get update -y && apt-get install curl
      - run:
          name: Preparing
          command: $(which bash) .circleci/setup.sh
      - run: echo 'export PATH=$GOBIN:$PATH' >> $BASH_ENV
      - run: dep ensure -v
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload:
          file: $(pwd)/coverage.txt